// src/app/blog/[slug]/NBlockOne.tsx




import React from 'react';

import type { INBlockProps } from './types'

import NBlockHeading from './NBlockHeading'
import NBlockParagraph from './NBlockParagraph';
import NBlockImage from './NBlockImage';
import NBlockCode from './NBlockCode';

const NBlockOne: React.FC<INBlockProps> = ({ id, type, ...args }) => {

  const isHeading = () => {
    return type.startsWith("heading_")
  }
  const headingProps = () => {
    return args[type] as any
  }


  return (
    <>
    {isHeading() && <NBlockHeading {...headingProps()} level={type} key={id}></NBlockHeading> }
    {args.paragraph && <NBlockParagraph {...args.paragraph} key={id}></NBlockParagraph>}
    {args.code && <NBlockCode {...args.code} key={id}></NBlockCode>}
    {args.image && <NBlockImage {...args.image} key={id}></NBlockImage>}
    </>
  );
};

export default NBlockOne;

// .vitepress/theme/components/NBlockOne.vue
<template>
    <template v-if="isHeading">
        <NBlockHeading v-bind="headingProps" :level="props.type" :key="props.id"></NBlockHeading>
    </template>
    <template v-else-if="props.paragraph">
        <NBlockParagraph v-bind="props.paragraph" :key="props.id"></NBlockParagraph>
    </template>
    <template v-else-if="props.code">
        <NBlockCode v-bind="props.code" :key="props.id"></NBlockCode>
    </template>
    <template v-else-if="props.image">
        <NBlockImage v-bind="props.image" :key="props.id"></NBlockImage>
    </template>
</template>

<script setup > 
import {computed} from 'vue'


const props = defineProps({
    id:String,
    type:{
        type: String,
        require: true
    },
    paragraph :Object,
    heading_1: Object,
    code: Object,
    heading_2: Object,
    heading_3: Object,
    image: Object,
});

const isHeading = computed(() => {
    return props.type.startsWith("heading_")
})
const headingProps = computed(() => {
    return props[props.type] 
})

</script>
