// src/app/blog/[slug]/NRichText.tsx




import React from 'react';

import type { IRichTextProps } from './types'


const NRichText: React.FC<IRichTextProps> = ({ type, href, plain_text, annotations, ...args }) => {

  const cls = (): string => {
    let res = Object.entries(annotations).filter(([key, val]) => {
      return val
    }).map(([key, val]) => {
      return key === 'code' ? val : key;
    });
    return res.join(' ');
  };



  return (
    <>
      {href ? (<a href={href} className={cls()} target="_blank">
        {plain_text}
      </a >) : (
        <span className={cls()}>
          {plain_text}
        </span>
      )
      }
    </>
  );
};

export default NRichText;

// .vitepress/theme/components/NRichText.vue
<template>
    <a v-if="href" :href="href" :class="cls" target="_blank">
        {{ props.plain_text }}
    </a>
    <span v-else :class="cls">
        {{ props.plain_text }}
    </span>
</template>

<script setup>

import {computed} from 'vue'

const props = defineProps({
    type: String,
    plain_text: String,
    href: String,
    annotations: Object,
    text: Object
})

const href = computed(() => {
    return props.href
})
const cls = computed(() => {
    let res = Object.entries(props.annotations).filter(([key, val]) => {
        return val
    }).map(([key, val]) => {
        return key === 'code' ? val : key;
    });
    return res;
})





</script>

<style scoped></style>
